/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mepsan.marwiz.general.report.warehousemovementreport.dao;

import com.mepsan.marwiz.general.core.presentation.SessionBean;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.support.JdbcDaoSupport;

/**
 *
 * @author esra.cabuk
 */
public class WarehouseMovementReportDao extends JdbcDaoSupport implements IWarehouseMovementReportDao {

    @Autowired
    SessionBean sessionBean;

    public void setSessionBean(SessionBean sessionBean) {
        this.sessionBean = sessionBean;
    }

    @Override
    public List<WarehouseMovementReport> findAll(int first, int pageSize, String sortField, String sortOrder, Map<String, Object> filters, String where, WarehouseMovementReport obj) {

        SimpleDateFormat sd = new SimpleDateFormat("MM.dd.yyyy HH:mm:ss");
        if (sortField == null) {
            sortField = "iwr.processdate";
            sortOrder = " DESC ";
        } else if (sortField.equals("quantity")) {

            sortField = "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                    + " wsi.alternativeunitquantity\n"
                    + "ELSE\n"
                    + "  iwm.quantity END \n";

        } else if (sortField.equals("unitPrice")) {
            sortField = "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                    + "         THEN \n"
                    + "(  SELECT \n"
                    + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                    + "                         ((COALESCE(sli2.unitprice,0)/(1+(sli2.taxrate)/100))*(sli2.exchangerate)) \n"
                    + "                     ELSE\n"
                    + "                         ((COALESCE(sli.unitprice,0)/(1+(sli.taxrate)/100))*(sli.exchangerate)) \n"
                    + "                     END\n"
                    + "                     FROM general.saleitem sli\n"
                    + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                    + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                    + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                    + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                    + "           THEN  ( \n"
                    + "                       SELECT \n"
                    + "                           (CASE WHEN  stck.unit_id <> invii.unit_id THEN stuc.quantity ELSE 1 END) *  --alternatif birim ise\n"
                    + "                            CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                    + "                               ((( invi2.totalprice * invi2.exchangerate * inv.exchangerate)+(invi2.discountprice*invi2.exchangerate) ) / invi2.quantity ) \n"
                    + "                            ELSE\n"
                    + "                               ((( invii.totalprice * invii.exchangerate * inv.exchangerate)+(invii.discountprice*invii.exchangerate) ) / invii.quantity ) \n"
                    + "                            END\n"
                    + "                          FROM finance.invoiceitem invii\n"
                    + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                    + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                    + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                    + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                    + "                       )\n"
                    + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                    + "            THEN                 	\n"
                    + "            	 ((COALESCE(wsi.currentprice, 0) * COALESCE(wsi.exchangerate, 1))/(1+(wsi.taxrate)/100)) \n"
                    + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                    + "             THEN\n"
                    + "             CASE WHEN stkin.is_taxincluded = FALSE\n"
                    + "                 THEN   COALESCE(stkini.currentpricelistprice,0)\n"
                    + "                   ELSE \n"
                    + "                  (COALESCE(stkini.currentpricelistprice,0)/(1+(ptg.rate)/100))\n"
                    + "                   END  \n"
                    + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                    + "             THEN   \n"
                    + "              CASE WHEN stkout.is_taxincluded = FALSE\n"
                    + "                  THEN  COALESCE(stkouti.currentpricelistprice,0)\n"
                    + "                   ELSE \n"
                    + "                  (COALESCE(stkouti.currentpricelistprice,0)/(1+(stg.rate)/100))\n"
                    + "                   END  \n"
                    + "      WHEN iwr.type_id  = 8 \n"
                    + "            THEN \n"
                    + "            (SELECT \n"
                    + "              (COALESCE(wti.currentprice, 0) * COALESCE(wti.exchangerate, 1))\n"
                    + "             FROM inventory.warehousetransferiteminfo wti\n"
                    + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                    + "       ELSE 0  END \n";
        } else if (sortField.equals("totalTax")) {

            sortField = "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                    + "         THEN \n"
                    + " (  SELECT \n"
                    + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                    + "                          COALESCE(sli2.totaltax,0) \n"
                    + "                     ELSE\n"
                    + "                          COALESCE(sli.totaltax,0) \n"
                    + "                     END\n"
                    + "                     FROM general.saleitem sli\n"
                    + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                    + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                    + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                    + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                    + "           THEN  ( \n"
                    + "                       SELECT \n"
                    + "                            CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                    + "                               COALESCE(invi2.totaltax,0)\n"
                    + "                            ELSE\n"
                    + "                               COALESCE(invii.totaltax,0)\n"
                    + "                            END\n"
                    + "                          FROM finance.invoiceitem invii\n"
                    + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                    + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                    + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                    + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                    + "                       )\n"
                    + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                    + "            THEN                 	\n"
                    + "            (COALESCE(wsi.currentprice,0) - (COALESCE(wsi.currentprice,0)/(1+(wsi.taxrate)/100))) * wsi.alternativeunitquantity \n"
                    + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL\n"
                    + "             THEN\n"
                    + "               CASE WHEN stkin.is_taxincluded = FALSE\n"
                    + "                     THEN (COALESCE(stkini.currentpricelistprice,0) * ((ptg.rate)/100))*iwm.quantity\n"
                    + "                   ELSE \n"
                    + "                         (COALESCE(stkini.currentpricelistprice,0) - (COALESCE(stkini.currentpricelistprice,0)/(1+(ptg.rate)/100))) * iwm.quantity \n"
                    + "                   END  \n"
                    + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                    + "             THEN                \n"
                    + "            CASE WHEN stkout.is_taxincluded = FALSE\n"
                    + "                     THEN (COALESCE(stkouti.currentpricelistprice,0) * ((stg.rate)/100))*iwm.quantity\n"
                    + "                   ELSE \n"
                    + "                         (COALESCE(stkouti.currentpricelistprice,0) - (COALESCE(stkouti.currentpricelistprice,0)/(1+(stg.rate)/100))) * iwm.quantity \n"
                    + "                   END     \n"
                    + "        WHEN iwr.type_id  = 8 \n"
                    + "            THEN    \n"
                    + "            (SELECT \n"
                    + "              (COALESCE(wti.currentprice,0) * ((wti.taxrate)/100))*iwm.quantity \n"
                    + "            FROM inventory.warehousetransferiteminfo wti\n"
                    + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                    + "                       ELSE 0  END \n";

        } else if (sortField.equals("totalPrice")) {

            sortField = "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                    + "         THEN \n"
                    + " (  SELECT \n"
                    + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                    + "                          COALESCE(sli2.totalmoney ,0) \n"
                    + "                     ELSE\n"
                    + "                          COALESCE(sli.totalmoney ,0) \n"
                    + "                     END\n"
                    + "                     FROM general.saleitem sli\n"
                    + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                    + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                    + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                    + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                    + "           THEN  ( \n"
                    + "                       SELECT \n"
                    + "                            CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                    + "                               invi2.totalmoney\n"
                    + "                            ELSE\n"
                    + "                               invii.totalmoney\n"
                    + "                            END\n"
                    + "                          FROM finance.invoiceitem invii\n"
                    + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                    + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                    + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                    + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                    + "                       )\n"
                    + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                    + "            THEN                 	\n"
                    + "               wsi.totalmoney\n"
                    + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                    + "             THEN\n"
                    + "             CASE WHEN stkin.is_taxincluded = FALSE\n"
                    + "                 THEN   \n"
                    + "                 (COALESCE(stkini.currentpricelistprice)+(COALESCE(stkini.currentpricelistprice,0)*(ptg.rate/100)))*iwm.quantity\n"
                    + "                   ELSE \n"
                    + "                  (COALESCE(stkini.currentpricelistprice,0)*iwm.quantity)\n"
                    + "                   END  \n"
                    + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                    + "             THEN   \n"
                    + "              CASE WHEN stkout.is_taxincluded = FALSE\n"
                    + "                  THEN \n"
                    + "                 (COALESCE(stkouti.currentpricelistprice)+(COALESCE(stkouti.currentpricelistprice,0)*(stg.rate/100)))*iwm.quantity\n"
                    + "                   ELSE \n"
                    + "                  (COALESCE(stkouti.currentpricelistprice,0)*iwm.quantity)\n"
                    + "                   END  \n"
                    + "      WHEN iwr.type_id  = 8 \n"
                    + "            THEN       \n"
                    + "            (SELECT\n"
                    + "             (COALESCE(wti.currentprice,0)+(COALESCE(wti.currentprice,0)*(wti.taxrate/100)))*iwm.quantity\n"
                    + "              FROM inventory.warehousetransferiteminfo wti\n"
                    + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                    + "       ELSE 0  END  \n";

        }

        String sql = "SELECT \n"
                + "iwm.id as iwmid,\n"
                + "iwr.processdate as iwrprocessdate,\n"
                + "iwm.is_direction as iwmis_direction,\n"
                + "iwm.warehouse_id as iwmwarehouse_id,\n"
                + "iw.name as iwname,\n"
                + "iwm.stock_id as iwmstock_id,\n"
                + "stck.name as stckname,\n"
                + "stck.barcode AS stckbarcode,\n"
                + "stck.code AS stckcode,\n"
                + "stck.centerproductcode AS stckcenterproductcode,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + " wsi.unit_id \n"
                + "ELSE\n"
                + " stck.unit_id END AS stckunit_id,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + " guntw.sortname\n "
                + "ELSE\n"
                + " gunt.sortname END AS guntsortname,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + " guntw.unitrounding \n"
                + "ELSE\n"
                + " gunt.unitrounding END AS guntunitsorting,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + " wsi.alternativeunitquantity\n"
                + "ELSE\n"
                + "  iwm.quantity END as iwmquantity,\n"
                + "(SELECT general.find_category(iwm.stock_id, 1, ?)) AS category,\n"
                + "stck.brand_id AS stckbrand_id,\n"
                + "br.name AS brname,\n"
                + "stck.supplier_id AS supplier_id,\n"
                + "acc.name AS accname,\n"
                + "stck.centralsupplier_id AS stckcentralsupplier_id, \n"
                + "cspp.name AS csppname,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + "(  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                         ((COALESCE(sli2.unitprice,0)/(1+(sli2.taxrate)/100))*(sli2.exchangerate)) \n"
                + "                     ELSE\n"
                + "                         ((COALESCE(sli.unitprice,0)/(1+(sli.taxrate)/100))*(sli.exchangerate)) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                           (CASE WHEN  stck.unit_id <> invii.unit_id THEN stuc.quantity ELSE 1 END) *  --alternatif birim ise\n"
                + "                            CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               ((( invi2.totalprice * invi2.exchangerate * inv.exchangerate)+(invi2.discountprice*invi2.exchangerate) ) / invi2.quantity ) \n"
                + "                            ELSE\n"
                + "                               ((( invii.totalprice * invii.exchangerate * inv.exchangerate)+(invii.discountprice*invii.exchangerate) ) / invii.quantity ) \n"
                + "                            END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "            	 ((COALESCE(wsi.currentprice, 0) * COALESCE(wsi.exchangerate, 1))/(1+(wsi.taxrate)/100)) \n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                 THEN   COALESCE(stkini.currentpricelistprice,0)\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkini.currentpricelistprice,0)/(1+(ptg.rate)/100))\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "              CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                  THEN  COALESCE(stkouti.currentpricelistprice,0)\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkouti.currentpricelistprice,0)/(1+(stg.rate)/100))\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 8 \n"
                + "            THEN \n"
                + "            (SELECT \n"
                + "              (COALESCE(wti.currentprice, 0) * COALESCE(wti.exchangerate, 1))\n"
                + "             FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as price,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + " (  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                          COALESCE(sli2.totaltax,0) \n"
                + "                     ELSE\n"
                + "                          COALESCE(sli.totaltax,0) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               COALESCE(invi2.totaltax,0)\n"
                + "                          ELSE\n"
                + "                               COALESCE(invii.totaltax,0)\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "            (COALESCE(wsi.currentprice,0) - (COALESCE(wsi.currentprice,0)/(1+(wsi.taxrate)/100))) * wsi.alternativeunitquantity \n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL\n"
                + "             THEN\n"
                + "               CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                     THEN (COALESCE(stkini.currentpricelistprice,0) * ((ptg.rate)/100))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                         (COALESCE(stkini.currentpricelistprice,0) - (COALESCE(stkini.currentpricelistprice,0)/(1+(ptg.rate)/100))) * iwm.quantity \n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN                \n"
                + "            CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                     THEN (COALESCE(stkouti.currentpricelistprice,0) * ((stg.rate)/100))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                         (COALESCE(stkouti.currentpricelistprice,0) - (COALESCE(stkouti.currentpricelistprice,0)/(1+(stg.rate)/100))) * iwm.quantity \n"
                + "                   END     \n"
                + "        WHEN iwr.type_id  = 8 \n"
                + "            THEN    \n"
                + "            (SELECT \n"
                + "              (COALESCE(wti.currentprice,0) * ((wti.taxrate)/100))*iwm.quantity \n"
                + "            FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "                       ELSE 0  END as totaltax ,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + " (  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                          COALESCE(sli2.totalmoney ,0) \n"
                + "                     ELSE\n"
                + "                          COALESCE(sli.totalmoney ,0) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               invi2.totalmoney\n"
                + "                          ELSE\n"
                + "                               invii.totalmoney\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "               wsi.totalmoney\n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                 THEN   \n"
                + "                 (COALESCE(stkini.currentpricelistprice)+(COALESCE(stkini.currentpricelistprice,0)*(ptg.rate/100)))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkini.currentpricelistprice,0)*iwm.quantity)\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "              CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                  THEN \n"
                + "                 (COALESCE(stkouti.currentpricelistprice)+(COALESCE(stkouti.currentpricelistprice,0)*(stg.rate/100)))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkouti.currentpricelistprice,0)*iwm.quantity)\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 8 \n"
                + "            THEN       \n"
                + "            (SELECT\n"
                + "             (COALESCE(wti.currentprice,0)+(COALESCE(wti.currentprice,0)*(wti.taxrate/100)))*iwm.quantity\n"
                + "              FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as totalmoney, \n"
                + "       CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + "(  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                       sli2.currency_id \n"
                + "                     ELSE\n"
                + "                       sli.currency_id \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               invi2.currency_id\n"
                + "                          ELSE\n"
                + "                               invii.currency_id\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN  \n"
                + "            wsi.currency_id               	\n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             stkini.currentpricelistcurrency_id\n"
                + "            \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "             stkouti.currentpricelistcurrency_id\n"
                + "       WHEN iwr.type_id  = 8 \n"
                + "            THEN       \n"
                + "           (SELECT\n"
                + "              wti.currency_id \n"
                + "             FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as currency_id                         \n"
                + "FROM inventory.warehousemovement iwm\n"
                + "LEFT JOIN inventory.warehousereceipt iwr ON (iwm.warehousereceipt_id=iwr.id AND iwr.deleted=FALSE)\n"
                + "LEFT JOIN inventory.warehouse iw ON (iwm.warehouse_id=iw.id AND iw.deleted = False)\n"
                + "INNER JOIN inventory.stock stck ON (iwm.stock_id=stck.id)\n"
                + "LEFT JOIN general.unit gunt ON(gunt.id=stck.unit_id)\n"
                + "LEFT JOIN general.brand br ON(br.id = stck.brand_id AND br.deleted = False)\n"
                + "LEFT JOIN general.account acc ON (acc.id = stck.supplier_id)\n"
                + "LEFT JOIN general.centralsupplier cspp ON (cspp.id = stck.centralsupplier_id)\n"
                + "  ------Satış Fişi--------\n"
                + "    LEFT JOIN finance.receipt_warehousereceipt_con rwc ON(rwc.warehousereceipt_id =iwr.id AND rwc.deleted = FALSE)\n"
                + "    LEFT JOIN finance.receipt rc ON(rwc.receipt_id = rc.id AND rc.deleted = FALSE)\n"
                + "    LEFT JOIN general.sale sl ON(sl.receipt_id = rc.id AND sl.deleted = FALSE AND sl.is_return = iwr.is_direction)\n"
                + "     -----İrsaliye-Fatura------------\n"
                + "    LEFT JOIN finance.waybill_warehousereceipt_con wwc ON(wwc.warehousereceipt_id = iwr.id AND wwc.deleted = FALSE)\n"
                + "    LEFT JOIN finance.waybill wb ON(wwc.waybill_id = wb.id AND wb.deleted=FALSE)\n"
                + "    LEFT JOIN finance.waybill_invoice_con wbc ON(wbc.waybill_id = wb.id AND wbc.deleted = FALSE)\n"
                + "    LEFT JOIN  finance.invoice inv ON(inv.id = wbc.invoice_id AND inv.deleted = FALSE)\n"
                + "    ------Sayım----- \n"
                + "     LEFT JOIN inventory.stocktaking stkin ON(stkin.inwarehousereceipt_id = iwr.id AND stkin.deleted = FALSE)\n"
                + "    LEFT JOIN inventory.stocktakingitem stkini ON(stkini.stocktaking_id=stkin.id AND stkini.stock_id=iwm.stock_id AND stkini.deleted=FALSE)\n"
                + "    LEFT JOIN inventory.stocktaking stkout ON(stkout.outwarehousereceipt_id = iwr.id AND stkout.deleted = FALSE)\n"
                + "    LEFT JOIN inventory.stocktakingitem stkouti ON(stkouti.stocktaking_id=stkin.id AND stkouti.stock_id=iwm.stock_id AND stkouti.deleted=FALSE)\n"
                + "    ------ATIK------\n"
                + "    LEFT JOIN inventory.wasteiteminfo wsi ON(wsi.warehousemovement_id=iwm.id AND wsi.deleted=FALSE)\n"
                + "    LEFT JOIN general.unit guntw ON(wsi.unit_id=guntw.id AND guntw.deleted=FALSE)\n"
                + "    LEFT JOIN (SELECT \n"
                + "                                txg.rate AS rate,\n"
                + "                                stc.stock_id AS stock_id \n"
                + "                                FROM inventory.stock_taxgroup_con stc  \n"
                + "                                INNER JOIN inventory.taxgroup txg  ON (txg.id=stc.taxgroup_id AND txg.deleted = false)\n"
                + "                                WHERE stc.deleted = false\n"
                + "                                AND txg.type_id = 10 --kdv grubundan \n"
                + "                                AND stc.is_purchase = FALSE) stg ON(stg.stock_id = stck.id)\n"
                + "   LEFT JOIN (SELECT \n"
                + "                                txg.rate AS rate,\n"
                + "                                stc.stock_id AS stock_id \n"
                + "                                FROM inventory.stock_taxgroup_con stc  \n"
                + "                                INNER JOIN inventory.taxgroup txg  ON (txg.id=stc.taxgroup_id AND txg.deleted = false)\n"
                + "                                WHERE stc.deleted = false\n"
                + "                                AND txg.type_id = 10 --kdv grubundan \n"
                + "                                AND stc.is_purchase = TRUE) ptg ON(ptg.stock_id = stck.id)\n"
                + "WHERE iwm.deleted=FALSE AND iw.branch_id=? "
                + where + "\n"
                + "ORDER BY " + sortField + " " + sortOrder + " \n"
                + " limit " + pageSize + " offset " + first;
        Object[] param = new Object[]{sessionBean.getUser().getLastBranch().getId(), sessionBean.getUser().getLastBranch().getId()};
        List<WarehouseMovementReport> result = getJdbcTemplate().query(sql, param, new WarehouseMovementReportMapper());
        return result;
    }

    @Override
    public String exportData(String where, WarehouseMovementReport obj) {

        SimpleDateFormat sd = new SimpleDateFormat("MM.dd.yyyy HH:mm:ss");

        String sql = "SELECT \n"
                + "iwm.id as iwmid,\n"
                + "iwr.processdate as iwrprocessdate,\n"
                + "iwm.is_direction as iwmis_direction,\n"
                + "iwm.warehouse_id as iwmwarehouse_id,\n"
                + "iw.name as iwname,\n"
                + "iwm.stock_id as iwmstock_id,\n"
                + "stck.name as stckname,\n"
                + "stck.barcode AS stckbarcode,\n"
                + "stck.code AS stckcode,\n"
                + "stck.centerproductcode AS stckcenterproductcode,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + " wsi.unit_id \n"
                + "ELSE\n"
                + "stck.unit_id END AS stckunit_id,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + " guntw.sortname\n "
                + "ELSE\n"
                + " gunt.sortname END AS guntsortname,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + " guntw.unitrounding \n"
                + "ELSE\n"
                + " gunt.unitrounding END AS guntunitsorting,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + " wsi.alternativeunitquantity\n"
                + "ELSE\n"
                + "  iwm.quantity END as iwmquantity,\n"
                + "(SELECT general.find_category(iwm.stock_id, 1, ?)) AS category,\n"
                + "stck.brand_id AS stckbrand_id,\n"
                + "br.name AS brname,\n"
                + "stck.supplier_id AS supplier_id,\n"
                + "acc.name AS accname,\n"
                + "stck.centralsupplier_id AS stckcentralsupplier_id, \n"
                + "cspp.name AS csppname,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + "(  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                         ((COALESCE(sli2.unitprice,0)/(1+(sli2.taxrate)/100))*(sli2.exchangerate)) \n"
                + "                     ELSE\n"
                + "                         ((COALESCE(sli.unitprice,0)/(1+(sli.taxrate)/100))*(sli.exchangerate)) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                           (CASE WHEN  stck.unit_id <> invii.unit_id THEN stuc.quantity ELSE 1 END) *  --alternatif birim ise\n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               ((( invi2.totalprice * invi2.exchangerate * inv.exchangerate)+(invi2.discountprice*invi2.exchangerate) ) / invi2.quantity ) \n"
                + "                          ELSE\n"
                + "                               ((( invii.totalprice * invii.exchangerate * inv.exchangerate)+(invii.discountprice*invii.exchangerate) ) / invii.quantity ) \n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "         ((COALESCE(wsi.currentprice, 0) * COALESCE(wsi.exchangerate, 1))/(1+(wsi.taxrate)/100)) \n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                 THEN   COALESCE(stkini.currentpricelistprice,0)\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkini.currentpricelistprice,0)/(1+(ptg.rate)/100))\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "              CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                  THEN  COALESCE(stkouti.currentpricelistprice,0)\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkouti.currentpricelistprice,0)/(1+(stg.rate)/100))\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 8 \n"
                + "            THEN \n"
                + "            (SELECT \n"
                + "              (COALESCE(wti.currentprice, 0) * COALESCE(wti.exchangerate, 1))\n"
                + "             FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as price,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + " (  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                           COALESCE(sli2.totaltax,0) \n"
                + "                     ELSE\n"
                + "                            COALESCE(sli.totaltax,0) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               COALESCE(invi2.totaltax,0)\n"
                + "                          ELSE\n"
                + "                               COALESCE(invii.totaltax,0)\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "            (COALESCE(wsi.currentprice,0) - (COALESCE(wsi.currentprice,0)/(1+(wsi.taxrate)/100))) * wsi.alternativeunitquantity \n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL\n"
                + "             THEN\n"
                + "               CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                     THEN (COALESCE(stkini.currentpricelistprice,0) * ((ptg.rate)/100))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                         (COALESCE(stkini.currentpricelistprice,0) - (COALESCE(stkini.currentpricelistprice,0)/(1+(ptg.rate)/100))) * iwm.quantity \n"
                + "                   END  \n"
                + "\n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN                \n"
                + "            CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                     THEN (COALESCE(stkouti.currentpricelistprice,0) * ((stg.rate)/100))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                         (COALESCE(stkouti.currentpricelistprice,0) - (COALESCE(stkouti.currentpricelistprice,0)/(1+(stg.rate)/100))) * iwm.quantity \n"
                + "                   END     \n"
                + "        WHEN iwr.type_id  = 8 \n"
                + "            THEN    \n"
                + "            (SELECT \n"
                + "              (COALESCE(wti.currentprice,0) * ((wti.taxrate)/100))*iwm.quantity \n"
                + "            FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "                       ELSE 0  END as totaltax ,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + " (  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                          COALESCE(sli2.totalmoney ,0) \n"
                + "                     ELSE\n"
                + "                          COALESCE(sli.totalmoney ,0) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               invi2.totalmoney\n"
                + "                          ELSE\n"
                + "                               invii.totalmoney\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "               wsi.totalmoney\n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                 THEN   \n"
                + "                 (COALESCE(stkini.currentpricelistprice)+(COALESCE(stkini.currentpricelistprice,0)*(ptg.rate/100)))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkini.currentpricelistprice,0)*iwm.quantity)\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "              CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                  THEN \n"
                + "                 (COALESCE(stkouti.currentpricelistprice)+(COALESCE(stkouti.currentpricelistprice,0)*(stg.rate/100)))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkouti.currentpricelistprice,0)*iwm.quantity)\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 8 \n"
                + "            THEN       \n"
                + "            (SELECT\n"
                + "             (COALESCE(wti.currentprice,0)+(COALESCE(wti.currentprice,0)*(wti.taxrate/100)))*iwm.quantity\n"
                + "              FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as totalmoney, \n"
                + "       \n"
                + "       CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + "(  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                          sli2.currency_id \n"
                + "                     ELSE\n"
                + "                          sli.currency_id\n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                           invi2.currency_id\n"
                + "                          ELSE\n"
                + "                           invii.currency_id\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN  \n"
                + "            wsi.currency_id               	\n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             stkini.currentpricelistcurrency_id\n"
                + "            \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "             stkouti.currentpricelistcurrency_id\n"
                + "       WHEN iwr.type_id  = 8 \n"
                + "            THEN       \n"
                + "           (SELECT\n"
                + "            COALESCE(wti.currency_id,0) \n"
                + "             FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as currency_id                         \n"
                + "FROM inventory.warehousemovement iwm\n"
                + "LEFT JOIN inventory.warehousereceipt iwr ON (iwm.warehousereceipt_id=iwr.id AND iwr.deleted=FALSE)\n"
                + "LEFT JOIN inventory.warehouse iw ON (iwm.warehouse_id=iw.id AND iw.deleted = False)\n"
                + "INNER JOIN inventory.stock stck ON (iwm.stock_id=stck.id)\n"
                + "LEFT JOIN general.unit gunt ON(gunt.id=stck.unit_id)\n"
                + "LEFT JOIN general.brand br ON(br.id = stck.brand_id AND br.deleted = False)\n"
                + "LEFT JOIN general.account acc ON (acc.id = stck.supplier_id)\n"
                + "LEFT JOIN general.centralsupplier cspp ON (cspp.id = stck.centralsupplier_id)\n"
                + "  ------Satış Fişi--------\n"
                + "    LEFT JOIN finance.receipt_warehousereceipt_con rwc ON(rwc.warehousereceipt_id =iwr.id AND rwc.deleted = FALSE)\n"
                + "    LEFT JOIN finance.receipt rc ON(rwc.receipt_id = rc.id AND rc.deleted = FALSE)\n"
                + "    LEFT JOIN general.sale sl ON(sl.receipt_id = rc.id AND sl.deleted = FALSE AND sl.is_return = iwr.is_direction)\n"
                + "     -----İrsaliye-Fatura------------\n"
                + "    LEFT JOIN finance.waybill_warehousereceipt_con wwc ON(wwc.warehousereceipt_id = iwr.id AND wwc.deleted = FALSE)\n"
                + "    LEFT JOIN finance.waybill wb ON(wwc.waybill_id = wb.id AND wb.deleted=FALSE)\n"
                + "    LEFT JOIN finance.waybill_invoice_con wbc ON(wbc.waybill_id = wb.id AND wbc.deleted = FALSE)\n"
                + "    LEFT JOIN  finance.invoice inv ON(inv.id = wbc.invoice_id AND inv.deleted = FALSE)\n"
                + "    ------Sayım----- \n"
                + "     LEFT JOIN inventory.stocktaking stkin ON(stkin.inwarehousereceipt_id = iwr.id AND stkin.deleted = FALSE)\n"
                + "    LEFT JOIN inventory.stocktakingitem stkini ON(stkini.stocktaking_id=stkin.id AND stkini.stock_id=iwm.stock_id AND stkini.deleted=FALSE)\n"
                + "    LEFT JOIN inventory.stocktaking stkout ON(stkout.outwarehousereceipt_id = iwr.id AND stkout.deleted = FALSE)\n"
                + "    LEFT JOIN inventory.stocktakingitem stkouti ON(stkouti.stocktaking_id=stkin.id AND stkouti.stock_id=iwm.stock_id AND stkouti.deleted=FALSE)\n"
                + "    ------ATIK------\n"
                + "    LEFT JOIN inventory.wasteiteminfo wsi ON(wsi.warehousemovement_id=iwm.id AND wsi.deleted=FALSE)\n"
                + "    LEFT JOIN general.unit guntw ON(wsi.unit_id=guntw.id AND guntw.deleted=FALSE)\n"
                + "    LEFT JOIN (SELECT \n"
                + "                                txg.rate AS rate,\n"
                + "                                stc.stock_id AS stock_id \n"
                + "                                FROM inventory.stock_taxgroup_con stc  \n"
                + "                                INNER JOIN inventory.taxgroup txg  ON (txg.id=stc.taxgroup_id AND txg.deleted = false)\n"
                + "                                WHERE stc.deleted = false\n"
                + "                                AND txg.type_id = 10 --kdv grubundan \n"
                + "                                AND stc.is_purchase = FALSE) stg ON(stg.stock_id = stck.id)\n"
                + "   LEFT JOIN (SELECT \n"
                + "                                txg.rate AS rate,\n"
                + "                                stc.stock_id AS stock_id \n"
                + "                                FROM inventory.stock_taxgroup_con stc  \n"
                + "                                INNER JOIN inventory.taxgroup txg  ON (txg.id=stc.taxgroup_id AND txg.deleted = false)\n"
                + "                                WHERE stc.deleted = false\n"
                + "                                AND txg.type_id = 10 --kdv grubundan \n"
                + "                                AND stc.is_purchase = TRUE) ptg ON(ptg.stock_id = stck.id)\n"
                + "WHERE iwm.deleted=FALSE AND iw.branch_id= " + sessionBean.getUser().getLastBranch().getId() + " \n"
                + where + "\n"
                + "ORDER BY iwr.processdate DESC,iwm.id\n";
        return sql;
    }

    @Override
    public DataSource getDatasource() {
        return getDataSource();
    }

    @Override
    public List<WarehouseMovementReport> totals(String where, WarehouseMovementReport obj) {
        SimpleDateFormat sd = new SimpleDateFormat("MM.dd.yyyy HH:mm:ss");

        String sql = "SELECT \n"
                + "COUNT(iwm.id) as iwmid,\n"
                + "CASE WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL THEN\n"
                + "  wsi.alternativeunitquantity\n"
                + "ELSE\n"
                + "  iwm.quantity END as iwmquantity,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + "(  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                         ((COALESCE(sli2.unitprice,0)/(1+(sli2.taxrate)/100))*(sli2.exchangerate)) \n"
                + "                     ELSE\n"
                + "                         ((COALESCE(sli.unitprice,0)/(1+(sli.taxrate)/100))*(sli.exchangerate)) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                           (CASE WHEN  stck.unit_id <> invii.unit_id THEN stuc.quantity ELSE 1 END) *  --alternatif birim ise\n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               ((( invi2.totalprice * invi2.exchangerate * inv.exchangerate)+(invi2.discountprice*invi2.exchangerate) ) / invi2.quantity ) \n"
                + "                          ELSE\n"
                + "                               ((( invii.totalprice * invii.exchangerate * inv.exchangerate)+(invii.discountprice*invii.exchangerate) ) / invii.quantity ) \n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "            	(COALESCE(wsi.currentprice, 0) * COALESCE(wsi.exchangerate, 1)) \n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                 THEN   COALESCE(stkini.currentpricelistprice,0)\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkini.currentpricelistprice,0)/(1+(ptg.rate)/100))\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "              CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                  THEN  COALESCE(stkouti.currentpricelistprice,0)\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkouti.currentpricelistprice,0)/(1+(stg.rate)/100))\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 8 \n"
                + "            THEN \n"
                + "            (SELECT \n"
                + "              (COALESCE(wti.currentprice, 0) * COALESCE(wti.exchangerate, 1))\n"
                + "             FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as price,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + " (  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                          COALESCE(sli2.totaltax,0) \n"
                + "                     ELSE\n"
                + "                          COALESCE(sli.totaltax,0) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               COALESCE(invi2.totaltax,0)\n"
                + "                          ELSE\n"
                + "                               COALESCE(invii.totaltax,0)\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "            (COALESCE(wsi.currentprice,0) - (COALESCE(wsi.currentprice,0)/(1+(wsi.taxrate)/100))) * wsi.alternativeunitquantity \n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL\n"
                + "             THEN\n"
                + "               CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                     THEN (COALESCE(stkini.currentpricelistprice,0) * ((ptg.rate)/100))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                         (COALESCE(stkini.currentpricelistprice,0) - (COALESCE(stkini.currentpricelistprice,0)/(1+(ptg.rate)/100))) * iwm.quantity \n"
                + "                   END  \n"
                + "\n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN                \n"
                + "            CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                     THEN (COALESCE(stkouti.currentpricelistprice,0) * ((stg.rate)/100))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                         (COALESCE(stkouti.currentpricelistprice,0) - (COALESCE(stkouti.currentpricelistprice,0)/(1+(stg.rate)/100))) * iwm.quantity \n"
                + "                   END     \n"
                + "        WHEN iwr.type_id  = 8 \n"
                + "            THEN    \n"
                + "            (SELECT \n"
                + "              (COALESCE(wti.currentprice,0) * ((wti.taxrate)/100))*iwm.quantity \n"
                + "            FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "                       ELSE 0  END as totaltax ,\n"
                + "CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + " (  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                          COALESCE(sli2.totalmoney ,0) \n"
                + "                     ELSE\n"
                + "                          COALESCE(sli.totalmoney ,0) \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               invi2.totalmoney\n"
                + "                          ELSE\n"
                + "                               invii.totalmoney\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN                 	\n"
                + "               wsi.totalmoney\n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             CASE WHEN stkin.is_taxincluded = FALSE\n"
                + "                 THEN   \n"
                + "                 (COALESCE(stkini.currentpricelistprice)+(COALESCE(stkini.currentpricelistprice,0)*(ptg.rate/100)))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkini.currentpricelistprice,0)*iwm.quantity)\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "              CASE WHEN stkout.is_taxincluded = FALSE\n"
                + "                  THEN \n"
                + "                 (COALESCE(stkouti.currentpricelistprice)+(COALESCE(stkouti.currentpricelistprice,0)*(stg.rate/100)))*iwm.quantity\n"
                + "                   ELSE \n"
                + "                  (COALESCE(stkouti.currentpricelistprice,0)*iwm.quantity)\n"
                + "                   END  \n"
                + "      WHEN iwr.type_id  = 8 \n"
                + "            THEN       \n"
                + "            (SELECT\n"
                + "             (COALESCE(wti.currentprice,0)+(COALESCE(wti.currentprice,0)*(wti.taxrate/100)))*iwm.quantity\n"
                + "              FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as totalmoney, \n"
                + "       \n"
                + "       CASE  WHEN iwr.type_id  = 61 AND (rc.id) IS NOT NULL \n"
                + "         THEN \n"
                + "(  SELECT \n"
                + "                     CASE WHEN sli.is_calcincluded = TRUE AND sl2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                       sli2.currency_id \n"
                + "                     ELSE\n"
                + "                       sli.currency_id \n"
                + "                     END\n"
                + "                     FROM general.saleitem sli\n"
                + "                     INNER JOIN general.sale sl2 ON(sl2.id = sli.sale_id AND sl2.deleted=FALSE)\n"
                + "                     LEFT JOIN general.saleitem sli2 ON(sli2.differentsaleitem_id = sli.id AND sli2.deleted=FALSE)\n"
                + "      	             WHERE sli.sale_id=sl.id AND sli.stock_id = iwm.stock_id AND sli.deleted = FALSE LIMIT 1 )\n"
                + "     WHEN iwr.type_id  = 61 AND (inv.id) IS NOT NULL\n"
                + "           THEN  ( \n"
                + "                       SELECT \n"
                + "                          CASE WHEN invii.is_calcincluded = TRUE AND inv2.differentdate BETWEEN '" + sd.format(obj.getBeginDate()) + "' AND '" + sd.format(obj.getEndDate()) + "' THEN \n"
                + "                               invi2.currency_id\n"
                + "                          ELSE\n"
                + "                               invii.currency_id\n"
                + "                          END\n"
                + "                          FROM finance.invoiceitem invii\n"
                + "                          INNER JOIN finance.invoice inv2 ON(inv2.id = invii.invoice_id AND inv2.deleted=FALSE)\n"
                + "                          LEFT JOIN inventory.stock_unit_con stuc ON(stuc.stock_id = invii.stock_id AND stuc.unit_id =  invii.unit_id  AND stuc.deleted = FALSE) \n"
                + "                          LEFT JOIN finance.invoiceitem invi2 ON(invi2.differentinvoiceitem_id = invii.id AND invi2.deleted=FALSE)\n"
                + "      	         	      WHERE invii.invoice_id = inv.id AND invii.stock_id = iwm.stock_id AND invii.deleted = FALSE LIMIT 1 \n"
                + "                       )\n"
                + "      WHEN iwr.type_id  = 76 AND (wsi.id) IS NOT NULL\n"
                + "            THEN  \n"
                + "            wsi.currency_id               	\n"
                + "      WHEN iwr.type_id  = 7 AND (stkin.id) IS NOT NULL \n"
                + "             THEN\n"
                + "             stkini.currentpricelistcurrency_id\n"
                + "            \n"
                + "      WHEN iwr.type_id  = 7 AND (stkout.id) IS NOT NULL\n"
                + "             THEN   \n"
                + "             stkouti.currentpricelistcurrency_id\n"
                + "       WHEN iwr.type_id  = 8 \n"
                + "            THEN       \n"
                + "           (SELECT\n"
                + "            COALESCE(wti.currency_id,0) \n"
                + "             FROM inventory.warehousetransferiteminfo wti\n"
                + "             WHERE wti.warehousemovement_id=iwm.id AND wti.deleted=FALSE LIMIT 1)\n"
                + "       ELSE 0  END as currency_id                         \n"
                + "FROM inventory.warehousemovement iwm\n"
                + "LEFT JOIN inventory.warehousereceipt iwr ON (iwm.warehousereceipt_id=iwr.id AND iwr.deleted=FALSE)\n"
                + "LEFT JOIN inventory.warehouse iw ON (iwm.warehouse_id=iw.id AND iw.deleted = False)\n"
                + "INNER JOIN inventory.stock stck ON (iwm.stock_id=stck.id)\n"
                + "LEFT JOIN general.unit gunt ON(gunt.id=stck.unit_id)\n"
                + "LEFT JOIN general.brand br ON(br.id = stck.brand_id AND br.deleted = False)\n"
                + "LEFT JOIN general.account acc ON (acc.id = stck.supplier_id)\n"
                + "LEFT JOIN general.centralsupplier cspp ON (cspp.id = stck.centralsupplier_id)\n"
                + "  ------Satış Fişi--------\n"
                + "    LEFT JOIN finance.receipt_warehousereceipt_con rwc ON(rwc.warehousereceipt_id =iwr.id AND rwc.deleted = FALSE)\n"
                + "    LEFT JOIN finance.receipt rc ON(rwc.receipt_id = rc.id AND rc.deleted = FALSE)\n"
                + "    LEFT JOIN general.sale sl ON(sl.receipt_id = rc.id AND sl.deleted = FALSE AND sl.is_return = iwr.is_direction)\n"
                + "     -----İrsaliye-Fatura------------\n"
                + "    LEFT JOIN finance.waybill_warehousereceipt_con wwc ON(wwc.warehousereceipt_id = iwr.id AND wwc.deleted = FALSE)\n"
                + "    LEFT JOIN finance.waybill wb ON(wwc.waybill_id = wb.id AND wb.deleted=FALSE)\n"
                + "    LEFT JOIN finance.waybill_invoice_con wbc ON(wbc.waybill_id = wb.id AND wbc.deleted = FALSE)\n"
                + "    LEFT JOIN  finance.invoice inv ON(inv.id = wbc.invoice_id AND inv.deleted = FALSE)\n"
                + "    ------Sayım----- \n"
                + "     LEFT JOIN inventory.stocktaking stkin ON(stkin.inwarehousereceipt_id = iwr.id AND stkin.deleted = FALSE)\n"
                + "    LEFT JOIN inventory.stocktakingitem stkini ON(stkini.stocktaking_id=stkin.id AND stkini.stock_id=iwm.stock_id AND stkini.deleted=FALSE)\n"
                + "    LEFT JOIN inventory.stocktaking stkout ON(stkout.outwarehousereceipt_id = iwr.id AND stkout.deleted = FALSE)\n"
                + "    LEFT JOIN inventory.stocktakingitem stkouti ON(stkouti.stocktaking_id=stkin.id AND stkouti.stock_id=iwm.stock_id AND stkouti.deleted=FALSE)\n"
                + "    ------ATIK------\n"
                + "    LEFT JOIN inventory.wasteiteminfo wsi ON(wsi.warehousemovement_id=iwm.id AND wsi.deleted=FALSE)\n"
                + "    LEFT JOIN general.unit guntw ON(wsi.unit_id=guntw.id AND guntw.deleted=FALSE)\n"
                + "    LEFT JOIN (SELECT \n"
                + "                                txg.rate AS rate,\n"
                + "                                stc.stock_id AS stock_id \n"
                + "                                FROM inventory.stock_taxgroup_con stc  \n"
                + "                                INNER JOIN inventory.taxgroup txg  ON (txg.id=stc.taxgroup_id AND txg.deleted = false)\n"
                + "                                WHERE stc.deleted = false\n"
                + "                                AND txg.type_id = 10 --kdv grubundan \n"
                + "                                AND stc.is_purchase = FALSE) stg ON(stg.stock_id = stck.id)\n"
                + "   LEFT JOIN (SELECT \n"
                + "                                txg.rate AS rate,\n"
                + "                                stc.stock_id AS stock_id \n"
                + "                                FROM inventory.stock_taxgroup_con stc  \n"
                + "                                INNER JOIN inventory.taxgroup txg  ON (txg.id=stc.taxgroup_id AND txg.deleted = false)\n"
                + "                                WHERE stc.deleted = false\n"
                + "                                AND txg.type_id = 10 --kdv grubundan \n"
                + "                                AND stc.is_purchase = TRUE) ptg ON(ptg.stock_id = stck.id)\n"
                + "WHERE iwm.deleted=FALSE AND iw.branch_id=? "
                + where + "\n"
                + "GROUP BY iwr.type_id,rc.id,inv.id,stck.unit_id,iwm.stock_id,\n"
                + "wsi.id,stkin.id, stkout.id,stkini.currentpricelistprice, stkouti.currentpricelistprice,ptg.rate,stg.rate,\n"
                + "iwm.quantity,stkini.currentpricelistcurrency_id, stkouti.currentpricelistcurrency_id\n"
                + ",iwm.id,sl.id\n";
        Object[] param = new Object[]{sessionBean.getUser().getLastBranch().getId()};
        List<WarehouseMovementReport> result = getJdbcTemplate().query(sql, param, new WarehouseMovementReportMapper());
        return result;

    }

    @Override
    public int count(String where) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public List<WarehouseMovementReport> findAll(int first, int pageSize, String sortField, String sortOrder, Map<String, Object> filters, String where) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
